SET FOREIGN_KEY_CHECKS=0;


DROP TABLE IF EXISTS PARTNERS;

DROP TABLE IF EXISTS DISTRI_ACCOUNTS;

DROP TABLE IF EXISTS DISTRIBUTION_ITERATIONS;

DROP TABLE IF EXISTS DISTRI_TRANSACTIONS;


DROP TABLE IF EXISTS flyway_schema_history;

SET FOREIGN_KEY_CHECKS=1;
