CREATE TABLE DISTRI_ACCOUNTS
  (
     DIST_ACCOUNT_ID VARCHAR(36) NOT NULL,
     OBJ_VERSION     INTEGER NOT NULL,
     PRIMARY KEY (DIST_ACCOUNT_ID)
  )
ENGINE=INNODB
DEFAULT CHARSET=UTF8;

CREATE TABLE DISTRI_TRANSACTIONS
  (
     DISTRI_TX_ID      VARCHAR(36) NOT NULL,
     OBJ_VERSION       INTEGER NOT NULL,
     DIST_ITERATION_ID VARCHAR(36),
     PRIMARY KEY (DISTRI_TX_ID)
  )
ENGINE=INNODB
DEFAULT CHARSET=UTF8;

CREATE TABLE DISTRIBUTION_ITERATIONS
  (
     DIST_ITERATION_ID VARCHAR(36) NOT NULL,
     CURRENT           BIT NOT NULL,
     OBJ_VERSION       INTEGER NOT NULL,
     DIST_ACCOUNT_ID   VARCHAR(36) NOT NULL,
     PRIMARY KEY (DIST_ITERATION_ID)
  )
ENGINE=INNODB
DEFAULT CHARSET=UTF8;

ALTER TABLE PARTNERS
  ADD COLUMN DIST_ACCOUNT_ID VARCHAR(36);

ALTER TABLE DISTRI_TRANSACTIONS
  ADD CONSTRAINT FK_DIST_TRANS_ITERATION_ID FOREIGN KEY (DIST_ITERATION_ID)
  REFERENCES DISTRIBUTION_ITERATIONS (DIST_ITERATION_ID);

ALTER TABLE DISTRIBUTION_ITERATIONS
  ADD CONSTRAINT FK_DIST_ITERATION_ACCOUNT_ID FOREIGN KEY (DIST_ACCOUNT_ID)
  REFERENCES DISTRI_ACCOUNTS (DIST_ACCOUNT_ID);

ALTER TABLE PARTNERS
  ADD CONSTRAINT FK_PARTNER_DIST_ACCOUNT_ID FOREIGN KEY(DIST_ACCOUNT_ID)
  REFERENCES DISTRI_ACCOUNTS(DIST_ACCOUNT_ID) ON DELETE CASCADE;
